##
# Basic
#
site_title: Pico Starter            # The title of your website
description: The picostarter theme is built with Zurb’s Foundation for Sites UI framework specifically for PicoCMS, provides incredible flexibility to kickstart your next website..
base_url: ~                         # Pico will try to guess its base URL, if this fails, override it here. Example: http://example.com/pico/.
rewrite_url: ~                      # A boolean (true or false) indicating whether URL rewriting is forced.
timezone: America/Chicago           # Your PHP installation might require you to manually specify a timezone.

##
# Theme
#
theme: bitsandpieces                # defaulter clutter bitsandpieces picostarter The name of your custom theme
theme_url: ~                        # Pico will try to guess the URL to the themes dir of your installation. If this fails, override it here. Example: http://example.com/pico/themes/.
twig_config:
    cache: false                    # Enable Twig template caching by specifying a path to a writable directory.
    autoescape: false               # Let Twig escape variables by default.
    debug: true                     # Enable Twig's debugging mode.

##
# Content
#
date_format: '%Y-%m-%d %l:%M %p'    # Pico's default date format. See also: http://php.net/manual/en/function.strftime.php. %F @ %l:%M %p
#time_format: '%l:%M %p'            # Future var to hold time only data (not date).
pages_order_by_meta: author         # Sort pages by meta value "author" (set "pages_order_by" to "meta")
pages_order_by: alpha               # Change how Pico sorts pages ("alpha" for alphabetical order, "date", or "meta")
pages_order: asc                    # Sort pages in ascending ("asc") or descending ("desc") order
content_dir: content/               # The path to Pico's content directory
content_ext: .md                    # The file extension of your Markdown files
content_config:
    extra: true                     # Use the Parsedown Extra parser to support extended markup. See https://michelf.ca/projects/php-markdown/extra/ for more info
    breaks: false                   # A boolean indicating whether breaks in the markup should be reflected in the parsed contents of the page.
    escape: false                   # Escape HTML markup in your content files; don't confuse this with some sort of safe mode, enabling this doesn't allow you to process untrusted user input!
    auto_urls: true                 # Automatically link URLs found in your markup.

##
# Plugins
#
Clutter.enabled: false              # Enable this plugin when using the Clutter theme.
pico_edit.enabled: false            # Plugin to allow front-end editing of files stored in /content dir.
ForceHttpsPlugin.enabled: false     # Plugin to help secure site.
#zz_pico_debug.enabled: false        # Debug

##
# Custom
#
my_tz: CST                          # Hard-code timezone abbreviation.
my_date_format: '%F'                # 2019-03-01
my_time_format: '%l:%M %p'          # 3:26 pm
