##
# Basic
#
site_title: Pico Starter            # The title of your website
description: Test description for use within the head > title tag.
base_url: ~                         # Pico will try to guess its base URL, if this fails, override it here. Example: http://example.com/pico/.
rewrite_url: ~                      # A boolean (true or false) indicating whether URL rewriting is forced.
timezone: America/Chicago           # Your PHP installation might require you to manually specify a timezone.

##
# Theme
#
theme: clutter                      # The name of your custom theme
theme_url: ~                        # Pico will try to guess the URL to the themes dir of your installation. If this fails, override it here. Example: http://example.com/pico/themes/.
theme_config:
    widescreen: true                # Default theme: Use more horizontal space (i.e. make the site container wider). Not sure if/how this setting effects other themes.
twig_config:
    cache: false                    # Enable Twig template caching by specifying a path to a writable directory.
    autoescape: false               # Let Twig escape variables by default.
    debug: true                     # Enable Twig's debugging mode.

##
# Content
#
date_format: '%F @ %l:%M %p'        # Pico's default date format. See also: http://php.net/manual/en/function.strftime.php.
#time_format: '%l:%M %p'
pages_order_by_meta: author         # Sort pages by meta value "author" (set "pages_order_by" to "meta").
pages_order_by: alpha               # Change how Pico sorts pages ("alpha" for alphabetical order, "date", or "meta").
pages_order: asc                    # Sort pages in ascending ("asc") or descending ("desc") order.
content_dir: content/               # The path to Pico's content directory.
content_ext: .md                    # The file extension of your Markdown files.
content_config:
    extra: true                     # Use the Parsedown Extra parser to support extended markup. See also: https://michelf.ca/projects/php-markdown/extra/.
    breaks: false                   # A boolean indicating whether breaks in the markup should be reflected in the parsed contents of the page.
    escape: false                   # Escape HTML markup in your content files; don't confuse this with some sort of safe mode, enabling this doesn't allow you to process untrusted user input!
    auto_urls: true                 # Automatically link URLs found in your markup.

##
# Plugins
#
DummyPlugin.enabled: false          # Force the plugin "DummyPlugin" to be disabled.
PicoDeprecated.enabled: false       # Force the plugin "DummyPlugin" to be disabled.
Clutter.enabled: true               # Enable this plugin when using the Clutter theme.

##
# Custom
#
my_custom_setting: Hello World!     # You can access custom settings in themes using {{ config.my_custom_setting }}.
my_tz: CST                          # Hard-code timezione abbreviation.
my_time_format: '%l:%M %p'
